export default function menu() {
  const content = document.getElementById('content');
  const menu = document.createElement('div');
  menu.className = 'menu';
  menu.id = 'wrapper';

  const breakfast = document.createElement('div');
  const bHeading = document.createElement('h3');
  bHeading.innerHTML = 'Breakfast';
  const breakfastItem1 = document.createElement('div');
  const bTitle1 = document.createElement('h3');
  bTitle1.innerHTML = 'Fruit Salad';
  const bContent1 = document.createElement('p');
  bContent1.innerHTML = 'with yoghurt honey and nuts.';
  const breakfastItem2 = document.createElement('div');
  const bTitle2 = document.createElement('h3');
  bTitle2.innerHTML = 'Hot Oat Oatmeal Porridge.';
  const bContent2 = document.createElement('p');
  bContent2.innerHTML = 'with almonds, raisins and brown sugar.';
  breakfastItem1.appendChild(bTitle1);
  breakfastItem1.appendChild(bContent1);
  breakfastItem2.appendChild(bTitle2);
  breakfastItem2.appendChild(bContent2);
  breakfast.appendChild(bHeading);
  breakfast.appendChild(breakfastItem1);
  breakfast.appendChild(breakfastItem2);
  const lunch = document.createElement('div');
  const lHeading = document.createElement('h3');
  lHeading.innerHTML = 'Lunch';
  const lunchItem1 = document.createElement('div');
  const lTitle1 = document.createElement('h3');
  lTitle1.innerHTML = 'Chicken Curry';
  const lContent1 = document.createElement('p');
  lContent1.innerHTML = 'with chapati or rice and salsa';
  const lunchItem2 = document.createElement('div');
  const lTitle2 = document.createElement('h3');
  lTitle2.innerHTML = 'Grilled Fish';
  const lContent2 = document.createElement('p');
  lContent2.innerHTML = 'spicy cajun grilled tilapia with garden salad & chips.';
  lunchItem1.appendChild(lTitle1);
  lunchItem1.appendChild(lContent1);
  lunchItem2.appendChild(lTitle2);
  lunchItem2.appendChild(lContent2);
  lunch.appendChild(lHeading);
  lunch.appendChild(lunchItem1);
  lunch.appendChild(lunchItem2);
  menu.appendChild(breakfast);
  menu.appendChild(lunch);
  content.appendChild(menu);
}